{{- if .Values.directConnect.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "towonel-agent.fullname" . }}-direct
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "towonel-agent.labels" . | nindent 4 }}
  {{- with .Values.directConnect.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
    - name: iroh
      port: {{ .Values.directConnect.irohPort }}
      targetPort: iroh
      protocol: UDP
      {{- with .Values.directConnect.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "towonel-agent.selectorLabels" . | nindent 4 }}
{{- end }}
