---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: towonel
gitea_urls:
  api: https://git.erwanleboucher.dev/api/v1
  download: https://git.erwanleboucher.dev

builds:
  - id: towonel-agent
    builder: rust
    dir: crates/towonel-agent
    binary: towonel-agent
    command: build
    targets:
      - x86_64-unknown-linux-gnu

  - id: towonel-node
    builder: rust
    dir: crates/towonel-node
    binary: towonel-node
    command: build
    targets:
      - x86_64-unknown-linux-gnu

  - id: towonel-cli
    builder: rust
    dir: crates/towonel-cli
    binary: towonel-cli
    command: build
    targets:
      - x86_64-unknown-linux-gnu

archives:
  - id: towonel
    ids:
      - towonel-agent
      - towonel-node
      - towonel-cli
