-- Add the tenant's ML-DSA-65 public key (1952 bytes) to invites.
--
-- Populated by `POST /v1/invites/redeem` before flipping the status to
-- 'redeemed'. `list_redeemed_tenants` reads it back at hub boot to
-- reconstruct the in-memory `OwnershipPolicy`.
--
-- NULL for pending/revoked invites (they pre-date the tenant choosing a
-- keypair).
--
-- See `docs/superpowers/specs/2026-04-15-pq-sigs-design.md` §5.2.
ALTER TABLE invites ADD COLUMN tenant_pq_public_key BLOB;
