use std::path::{Path, PathBuf};

use anyhow::{Context, anyhow};
use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64;
use serde::{Deserialize, Serialize};
use turbo_common::invite::EdgeInviteToken;

const DEFAULT_NODE_KEY: &str = "/var/lib/turbo-tunnel/node.key";
const DEFAULT_NODE_CONFIG: &str = "/etc/turbo-tunnel/node.toml";

pub async fn run(invite_str: &str, config_out: Option<&Path>) -> anyhow::Result<()> {
    let token = EdgeInviteToken::decode(invite_str).context("invalid edge invite token")?;
    println!("Contacting hub at {}...", token.hub_url);

    let key_path = PathBuf::from(DEFAULT_NODE_KEY);
    let config_path = config_out.map_or_else(|| PathBuf::from(DEFAULT_NODE_CONFIG), Path::to_path_buf);

    let secret_key = turbo_common::identity::load_or_generate_secret_key(&key_path)
        .with_context(|| format!("failed to load/generate node key at {}", key_path.display()))?;
    let node_id = secret_key.public();

    println!();
    println!("Generated node keypair:");
    println!("  Node ID:   {node_id}");
    println!("  Key saved: {} (0600)", key_path.display());
    println!();

    let redeem_url = format!(
        "{}/v1/edge-invites/redeem",
        token.hub_url.trim_end_matches('/')
    );
    let req = RedeemRequest {
        invite_id: B64.encode(token.invite_id),
        invite_secret: B64.encode(token.invite_secret),
        edge_node_id: node_id.to_string(),
    };
    let resp = reqwest::Client::new()
        .post(&redeem_url)
        .json(&req)
        .send()
        .await
        .with_context(|| format!("failed to POST {redeem_url}"))?;

    let status = resp.status();
    let body = resp.bytes().await?;
    if !status.is_success() {
        let err: serde_json::Value = serde_json::from_slice(&body).unwrap_or_default();
        return Err(anyhow!(
            "hub returned {status}: {}",
            serde_json::to_string_pretty(&err)?
        ));
    }
    let redeemed: RedeemResponse =
        serde_json::from_slice(&body).context("hub returned malformed redemption response")?;
    println!("✓ Registered as edge node \"{}\"", redeemed.name);

    write_node_config(&config_path, &key_path, &token.hub_url)?;
    println!("Config: {}", config_path.display());
    println!();
    println!(
        "Start the edge: turbo-node --config {}",
        config_path.display()
    );
    Ok(())
}

/// Write a starter `node.toml` for edge-only mode subscribing to a remote
/// hub. Refuses to overwrite an existing file.
fn write_node_config(path: &Path, key_path: &Path, hub_url: &str) -> anyhow::Result<()> {
    if path.exists() {
        return Err(anyhow!(
            "config file {} already exists; refusing to overwrite. \
             Move it aside or pass --config-out to a fresh path.",
            path.display()
        ));
    }
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    let content = format!(
        "# Auto-generated by `turbo-node init --edge-invite`. Edit as needed.\n\
        \n\
        [identity]\n\
        key_path = \"{}\"\n\
        \n\
        [hub]\n\
        enabled = false\n\
        \n\
        [edge]\n\
        enabled = true\n\
        listen_addr = \"0.0.0.0:443\"\n\
        # Subscribe to this hub for route updates (user-stories.md §5).\n\
        hub_url = \"{}\"\n",
        key_path.display(),
        hub_url.trim_end_matches('/'),
    );
    std::fs::write(path, content)?;
    Ok(())
}

#[derive(Serialize)]
struct RedeemRequest {
    invite_id: String,
    invite_secret: String,
    edge_node_id: String,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct RedeemResponse {
    status: String,
    name: String,
    hub_node_id: String,
}
